'''配置app服务'''
DEBUG = True
PORT = 8899
HOST = "0.0.0.0"
SECRET_KEY = "my api"
BUNDLE_ERRORS = True

'''配置数据库'''
DB_USER = 'root'
DB_PASSWORD = '123456'
DB_HOST = 'localhost'
DB_DB = 'test'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_POOL_SIZE = 1024
AUTH_SALT = 'AUTH_SALT'
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://'+DB_USER+':'+DB_PASSWORD+'@'+DB_HOST+'/'+DB_DB
